<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_swatch__image___4F2Tg</name>
   <tag></tag>
   <elementGuidId>3ac44a59-f1c1-4559-a909-b661f132948d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch__image___4F2Tg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/div[@class=&quot;app__childrenContainerNarrow___2Gjv4 app__childrenContainerWithTrimNarrow___2aYoL&quot;]/div[1]/div[@class=&quot;productView__productCardWrapperNarrow___1PEtG productView__nonEvoSku___2_TDm&quot;]/div[1]/div[1]/div[@class=&quot;newProductCard__secondaryBlockNarrow___Ag7vs newProductCard__adaptiveGutterNarrow___30mLk layout__adaptiveGutterPaddingAll___12ady layout__adaptiveGutterPadding___1evEM layout__adaptiveGutterPaddingRight___2Ourm layout__adaptiveGutterPaddingLeft___1KTBe layout__adaptiveGutterPaddingVertical___3o01V layout__adaptiveGutterPaddingTop___3ragO layout__adaptiveGutterPaddingBottom___2c1nd&quot;]/div[@class=&quot;swatchSelector__containerNarrow___3iFQi newProductCard__swatchesNarrow___2SA93&quot;]/div[@class=&quot;swatchGrid__swatchesNarrow___3VOgE swatchGrid__swatches___3Bmmv utilities__flexWrap___3I8rf utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;swatch__evo___2edoT utilities__pointer___1ctfY&quot;]/div[@class=&quot;swatch__swatch___EOSMo utilities__relative___1GEg3 utilities__flexContainer___2sCJV utilities__flexStatic___1S_9I&quot;]/div[@class=&quot;swatch__inner___35qkb utilities__relative___1GEg3&quot;]/div[@class=&quot;swatch__image___4F2Tg&quot;]</value>
   </webElementProperties>
</WebElementEntity>
