<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Esmaltes</name>
   <tag></tag>
   <elementGuidId>f164da8b-8d0a-40cc-838b-14e708101d8d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>menu__item___2wlde utilities__flexCenterVertical___2nEt- utilities__flexContainer___2sCJV utilities__bold___3ltf7 utilities__block___2NUBz typography__body___1MTtC theme__navText___32Qoi StyledLink-khUpca ddtewq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categoria/5547</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Esmaltes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/div[@class=&quot;Drawer__OuterDiv-fQULRK utilities__cover___WKDvY jxeJTN&quot;]/div[@class=&quot;Drawer__InnerDiv-QSCgb jfPdeQ&quot;]/div[@class=&quot;DrawerDiv-ihhGLG ZybrZ&quot;]/div[@class=&quot;TransitionContainer__NarrowScrollDiv-dvmQNx hDoneZ&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;menu__container___3qiFn layout__adaptiveGutter___3v1Qo layout__adaptiveGutterRight___ZCtdN layout__adaptiveGutterLeft___aW0BS&quot;]/a[@class=&quot;menu__item___2wlde utilities__flexCenterVertical___2nEt- utilities__flexContainer___2sCJV utilities__bold___3ltf7 utilities__block___2NUBz typography__body___1MTtC theme__navText___32Qoi StyledLink-khUpca ddtewq&quot;]</value>
   </webElementProperties>
</WebElementEntity>
