<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tienda</name>
   <tag></tag>
   <elementGuidId>f9ce96fa-dd1f-4bdc-bc8a-2db19f7948bc</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/tienda</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>utilities__block___2NUBz utilities__nopointer___uZbLY utilities__linkUnstyled___1aHoW</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tienda</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/div[@class=&quot;narrowNav__open___3uNnX narrowNav__menu___FVcY5 utilities__fixed___1nM3D theme__navBackground___qFmEe&quot;]/div[@class=&quot;narrowNav__wrapper___3LQLb utilities__fullHeight___NZTu9 utilities__fullWidth___3kUCi theme__navBorderColor___2Rp-j&quot;]/div[@class=&quot;TransitionContainer__NarrowScrollDiv-dvmQNx hDoneZ&quot;]/div[1]/div[1]/div[1]/div[1]/div[@class=&quot;menu__container___3qiFn layout__adaptiveGutter___3v1Qo layout__adaptiveGutterRight___ZCtdN layout__adaptiveGutterLeft___aW0BS&quot;]/div[@class=&quot;menu__primary___2hWIa typography__copy32___GJQ1d utilities__bold___3ltf7 theme__navText___32Qoi&quot;]/a[@class=&quot;utilities__block___2NUBz utilities__nopointer___uZbLY utilities__linkUnstyled___1aHoW&quot;]</value>
   </webElementProperties>
</WebElementEntity>
