<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_subtotal</name>
   <tag></tag>
   <elementGuidId>865087c1-94c3-400d-a535-ea83c48ac820</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cartTotals__valueNarrow___vtwSN cartTotals__value___QJxGy utilities__rightAlign___3FupO</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>£185.90</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn&quot;]/div[@class=&quot;app__childrenContainerNarrow___2Gjv4&quot;]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[@class=&quot;GutterDiv-uPqzs bOPyiR&quot;]/div[@class=&quot;checkoutViewNarrow__container___18Wyn&quot;]/div[@class=&quot;cartTotals__container___3ajgk&quot;]/div[@class=&quot;cartTotals__rowNarrow___1Meku cartTotals__rowBase___1GIWW utilities__flexContainer___2sCJV typography__tertiaryHeader___3Jilk utilities__bold___3ltf7&quot;]/div[@class=&quot;cartTotals__valueNarrow___vtwSN cartTotals__value___QJxGy utilities__rightAlign___3FupO&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='root']/div/div/div/div/div/div[6]/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove'])[4]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free delivery over £35 spend'])[1]/preceding::div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[6]/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
