<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_total</name>
   <tag></tag>
   <elementGuidId>ffc8d997-dc93-454f-b3ad-393bf21e5f08</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cartTotals__grandValueNarrow___1Ajf8 cartTotals__value___QJxGy utilities__rightAlign___3FupO typography__secondaryHeader___Tt_y7 utilities__bold___3ltf7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>£185.90</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn&quot;]/div[@class=&quot;app__childrenContainerNarrow___2Gjv4&quot;]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[@class=&quot;GutterDiv-uPqzs bOPyiR&quot;]/div[@class=&quot;checkoutViewNarrow__container___18Wyn&quot;]/div[@class=&quot;cartTotals__container___3ajgk&quot;]/div[@class=&quot;cartTotals__grandRowNarrow___1HKCh cartTotals__rowNarrow___1Meku cartTotals__rowBase___1GIWW utilities__flexContainer___2sCJV typography__tertiaryHeader___3Jilk utilities__bold___3ltf7&quot;]/div[@class=&quot;cartTotals__grandValueNarrow___1Ajf8 cartTotals__value___QJxGy utilities__rightAlign___3FupO typography__secondaryHeader___Tt_y7 utilities__bold___3ltf7&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='root']/div/div/div/div/div/div[6]/div[3]/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total'])[1]/following::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Place Order and Pay'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[6]/div[3]/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
