<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_16171819202122232425262</name>
   <tag></tag>
   <elementGuidId>a94006ca-d7d0-4065-afe9-d8ca267679ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@class = 'select__select___ZacEM utilities__absolute___2Nj_S utilities__cover___WKDvY utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9' and (text() = '1617181920212223242526272829303132333435363738394041424344454647484950' or . = '1617181920212223242526272829303132333435363738394041424344454647484950')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select__select___ZacEM utilities__absolute___2Nj_S utilities__cover___WKDvY utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment.expirationYear</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1617181920212223242526272829303132333435363738394041424344454647484950</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn&quot;]/div[@class=&quot;app__childrenContainerNarrow___2Gjv4&quot;]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[@class=&quot;checkoutOrderView__orderComponentContainer___3gofH&quot;]/div[@class=&quot;GutterDiv-uPqzs cRBQBu&quot;]/div[@class=&quot;form__container___31zeP utilities__relative___1GEg3&quot;]/div[1]/div[@class=&quot;containers__formVerticalSpacingAdaptive___2TxXH&quot;]/div[@class=&quot;creditCardFields__thirds___3J0_p containers__containerBorderCollapse___1PVDW utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;select__container___3lMpq utilities__relative___1GEg3 utilities__block___2NUBz&quot;]/select[@class=&quot;select__select___ZacEM utilities__absolute___2Nj_S utilities__cover___WKDvY utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9&quot;]</value>
   </webElementProperties>
</WebElementEntity>
