<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Nombre</name>
   <tag></tag>
   <elementGuidId>77c7c7cf-3368-45e9-90e8-42303913b2b5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nombre</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/ul[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/li[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/div[@class=&quot;dialog__backdrop___3ymQv utilities__absolute___2Nj_S utilities__cover___WKDvY utilities__flexCenterBoth___bT52v utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;dialog__mainNarrow___kBupJ dialog__main___2SIs0 utilities__relative___1GEg3&quot;]/div[2]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[2]/div[@class=&quot;form__container___31zeP utilities__relative___1GEg3&quot;]/div[@class=&quot;containers__formVerticalSpacingAdaptive___2TxXH loginForm__container___3mh3K&quot;]/div[@class=&quot;containers__containerBorderCollapse___1PVDW utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;layout__flexBasis50___1kUYj&quot;]/label[@class=&quot;textInput__container___1SC_K utilities__relative___1GEg3 utilities__block___2NUBz layout__heightControlAdaptive___3k245 utilities__fullWidth___3kUCi textInput__containerValid___3KDT5&quot;]/div[@class=&quot;textInput__label___1C_JP utilities__absolute___2Nj_S utilities__uppercase___3lD3P typography__labelCopy___1dstj typography__copy12___2kUwm utilities__flexCenterVertical___2nEt- utilities__flexContainer___2sCJV textInput__labelValid___3EW3U textInput__labelInactiveNarrow___jsuhe&quot;]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
