<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Antiedad</name>
   <tag></tag>
   <elementGuidId>2c1c487e-f0f0-4276-bf6e-9c3abf3abbf5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledLink-khUpca ddtewq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/categoria/5840</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Antiedad</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn app__containerWithTrimWide___1wGXG app__container___1iszn&quot;]/div[@class=&quot;NavBar__OuterDiv-iYytUm ovcze&quot;]/div[@class=&quot;MenuWide__MenuDiv-flXzGx hNqcYi&quot;]/div[@class=&quot;ShopMenuWide-es__StyledAdaptiveWrapper-jqlFHX bslhLy GutterDiv-uPqzs eAjzvm&quot;]/div[@class=&quot;submenu__container___rqzSn utilities__fullWidth___3kUCi utilities__flexColumn___2rDiE utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;submenuDepartment__main___39-bO utilities__flexContainer___2sCJV utilities__fullHeight___NZTu9&quot;]/div[@class=&quot;submenuDepartment__categories___2rrui utilities__flexGrow___2w8I0 utilities__flexColumn___2rDiE utilities__flexContainer___2sCJV utilities__flexWrap___3I8rf utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;submenuDepartment__category___vn7hi utilities__halfWidth___3wrHw&quot;]/div[@class=&quot;submenu__subheaderLink___3ICH4 submenu__subheader___1HS_S typography__copy14___3VCcc utilities__bold___3ltf7 theme__themeHover___2yDP1&quot;]/a[@class=&quot;StyledLink-khUpca ddtewq&quot;]</value>
   </webElementProperties>
</WebElementEntity>
