<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect</name>
   <tag></tag>
   <elementGuidId>b0a48df2-e52d-4799-a48e-a4bcdc3e16dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/ul[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/li[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/div[@class=&quot;dialog__backdrop___3ymQv utilities__absolute___2Nj_S utilities__cover___WKDvY utilities__flexCenterBoth___bT52v utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;dialog__mainNarrow___kBupJ dialog__main___2SIs0 utilities__relative___1GEg3&quot;]/div[@class=&quot;dialog__header___19PBt utilities__flexCenterVertical___2nEt- utilities__flexContainer___2sCJV theme__themeBackground___3002u&quot;]/div[@class=&quot;dialog__headerRightNarrow___2DXIk utilities__flexStatic___1S_9I&quot;]/div[@class=&quot;dialog__close___1LhUc utilities__flexCenterBoth___bT52v utilities__flexContainer___2sCJV utilities__pointer___1ctfY&quot;]/div[1]/svg[@class=&quot;icon__svg___cc1CR utilities__block___2NUBz utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9&quot;]/rect[1][count(. | //rect[@x = '-4.4' and @y = '11.9' and @transform = 'matrix(0.7071 -0.7071 0.7071 0.7071 -5.3585 12.9361)' and @width = '34.6' and @height = '2']) = count(//rect[@x = '-4.4' and @y = '11.9' and @transform = 'matrix(0.7071 -0.7071 0.7071 0.7071 -5.3585 12.9361)' and @width = '34.6' and @height = '2'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>-4.4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>11.9</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>transform</name>
      <type>Main</type>
      <value>matrix(0.7071 -0.7071 0.7071 0.7071 -5.3585 12.9361)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>34.6</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/ul[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/li[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/div[@class=&quot;dialog__backdrop___3ymQv utilities__absolute___2Nj_S utilities__cover___WKDvY utilities__flexCenterBoth___bT52v utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;dialog__mainNarrow___kBupJ dialog__main___2SIs0 utilities__relative___1GEg3&quot;]/div[@class=&quot;dialog__header___19PBt utilities__flexCenterVertical___2nEt- utilities__flexContainer___2sCJV theme__themeBackground___3002u&quot;]/div[@class=&quot;dialog__headerRightNarrow___2DXIk utilities__flexStatic___1S_9I&quot;]/div[@class=&quot;dialog__close___1LhUc utilities__flexCenterBoth___bT52v utilities__flexContainer___2sCJV utilities__pointer___1ctfY&quot;]/div[1]/svg[@class=&quot;icon__svg___cc1CR utilities__block___2NUBz utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9&quot;]/rect[1]</value>
   </webElementProperties>
</WebElementEntity>
