<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(root)divclassapp__conta_1</name>
   <tag></tag>
   <elementGuidId>38ad0833-2d4f-4a71-9dc6-c6298212e6ff</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/div[@class=&quot;navBar__container___2OWev utilities__fixed___1nM3D utilities__pinTopLeft___2dFnK utilities__fullWidth___3kUCi utilities__flexColReverse___1RTGl utilities__flexContainer___2sCJV theme__navBackground___qFmEe&quot;]/div[@class=&quot;navBar__barWrapperNarrow___237cs utilities__relative___1GEg3&quot;]/div[@class=&quot;barNarrow__container___FV-A2 utilities__flexContainer___2sCJV utilities__fullHeight___NZTu9&quot;]/div[@class=&quot;barNarrow__right___Tcy0z barNarrow__side___2ixyx utilities__flexCenterVertical___2nEt- utilities__flexContainer___2sCJV utilities__flexAlignRight___3TEh8 utilities__flexContainer___2sCJV layout__adaptiveGutterPaddingRight___2Ourm&quot;]/div[@class=&quot;barNarrow__menu___3BAeI utilities__flexCenterBoth___bT52v utilities__flexContainer___2sCJV layout__adaptiveGutterLeft___aW0BS utilities__pointer___1ctfY&quot;]/div[1]/svg[@class=&quot;icon__svg___cc1CR utilities__block___2NUBz utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
   </webElementProperties>
</WebElementEntity>
