<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aftershave</name>
   <tag></tag>
   <elementGuidId>339dd8be-841b-4822-a3ee-2561b2a40308</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PillarLinkBlock__StyledLink-bqdlqL typography__copy14___3VCcc gHbcIj StyledLink-khUpca ddtewq</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/category/1394</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aftershave</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/div[@class=&quot;Drawer__OuterDiv-fQULRK utilities__cover___WKDvY jxeJTN&quot;]/div[@class=&quot;Drawer__InnerDiv-QSCgb jfPdeQ&quot;]/div[@class=&quot;DrawerDiv-ihhGLG ZybrZ&quot;]/div[@class=&quot;TransitionContainer__NarrowScrollDiv-dvmQNx hDoneZ&quot;]/div[1]/div[1]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[@class=&quot;DepartmentMenuLinksNarrow__OuterDiv-iQxfMs eHSnnO&quot;]/div[2]/div[@class=&quot;PillarLinkBlock__SubPillarContainer-deoZqo hXmjtw&quot;]/a[@class=&quot;PillarLinkBlock__StyledLink-bqdlqL typography__copy14___3VCcc gHbcIj StyledLink-khUpca ddtewq&quot;]</value>
   </webElementProperties>
</WebElementEntity>
