<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>4d37d702-845c-4649-976b-2639aa4a4810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@color = 'colorWhite' and (text() = 'Continue' or . = 'Continue')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>StyledButton-gXzblK gMsrXs</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>colorWhite</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn&quot;]/ul[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/li[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/div[@class=&quot;sheet__container___1Dstb utilities__fixed___1nM3D utilities__cover___WKDvY utilities__flexCenterBoth___bT52v utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;sheet__main___1kYW3 utilities__fixed___1nM3D utilities__cover___WKDvY&quot;]/div[@class=&quot;sheet__content___2An5_ utilities__absolute___2Nj_S utilities__cover___WKDvY&quot;]/div[@class=&quot;layout__adaptiveGutterPaddingBottom___2c1nd GutterDiv-uPqzs bOPyiR&quot;]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[@class=&quot;form__container___31zeP utilities__relative___1GEg3&quot;]/div[1]/div[@class=&quot;footerButtons__container___1cfWE ButtonGroup__GroupDiv-cZHEKA OodrI&quot;]/button[@class=&quot;StyledButton-gXzblK gMsrXs&quot;]</value>
   </webElementProperties>
</WebElementEntity>
