<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_firstName (4)</name>
   <tag></tag>
   <elementGuidId>50faa18e-093a-4f0b-a862-270a9699289c</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput__input___cxJ09 utilities__resetBox___2gA-8 utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9 typography__inputCopy___dUIAv typography__copy14___3VCcc textInput__inputWithLabel___2uQ69</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tes</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn&quot;]/div[@class=&quot;app__childrenContainerNarrow___2Gjv4&quot;]/div[@class=&quot;GutterDiv-uPqzs bOPyiR&quot;]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[2]/div[@class=&quot;form__container___31zeP utilities__relative___1GEg3&quot;]/div[@class=&quot;containers__formVerticalSpacingAdaptive___2TxXH containers__containerForm___2gXsg&quot;]/div[@class=&quot;containers__containerBorderCollapse___1PVDW utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;layout__flexBasis50___1kUYj&quot;]/label[@class=&quot;textInput__container___1SC_K utilities__relative___1GEg3 utilities__block___2NUBz layout__heightControlAdaptive___3k245 utilities__fullWidth___3kUCi textInput__containerValid___3KDT5&quot;]/input[@class=&quot;textInput__input___cxJ09 utilities__resetBox___2gA-8 utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9 typography__inputCopy___dUIAv typography__copy14___3VCcc textInput__inputWithLabel___2uQ69&quot;]</value>
   </webElementProperties>
</WebElementEntity>
