<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_searchForm__input___2s6r (1)</name>
   <tag></tag>
   <elementGuidId>5401db32-e8dc-4152-a994-83624f473249</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocapitalize</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocorrect</name>
      <type>Main</type>
      <value>off</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchForm__input___2s6rs utilities__resetBox___2gA-8 utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9 typography__inputCopy___dUIAv typography__copy14___3VCcc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Find brands &amp; products</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pu</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn app__containerWithTrimWide___1wGXG app__container___1iszn&quot;]/div[@class=&quot;NavBar__OuterDiv-iYytUm jWomxD&quot;]/div[@class=&quot;SearchOverlay__StyledAdaptiveWrapper-kljcsI csGrvN GutterDiv-uPqzs kgiKYr&quot;]/div[@class=&quot;SearchOverlay__InnerDiv-dBlQnc girqkP&quot;]/div[@class=&quot;Row__RowDiv-bJIWhE gnPGGO&quot;]/div[@class=&quot;Col__ColDiv-fHCHMC hFJPUy&quot;]/form[@class=&quot;SearchOverlay__StyledSearchForm-hdKqME MUqaz&quot;]/input[@class=&quot;searchForm__input___2s6rs utilities__resetBox___2gA-8 utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9 typography__inputCopy___dUIAv typography__copy14___3VCcc&quot;]</value>
   </webElementProperties>
</WebElementEntity>
