<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_cvv</name>
   <tag></tag>
   <elementGuidId>e5419fa1-5cca-4af7-9d4a-c25e84a48ea3</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textInput__input___cxJ09 utilities__resetBox___2gA-8 utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9 typography__inputCopy___dUIAv typography__copy14___3VCcc textInput__inputWithLabel___2uQ69</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvv</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn&quot;]/div[@class=&quot;app__childrenContainerNarrow___2Gjv4&quot;]/div[@class=&quot;myAccountView__container___2QM0D layout__adaptiveGutterPaddingBottom___2c1nd utilities__relative___1GEg3&quot;]/div[@class=&quot;GutterDiv-uPqzs bOPyiR&quot;]/div[1]/div[3]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[@class=&quot;paymentDetails__collapse___3Vcvi utilities__relative___1GEg3&quot;]/div[@class=&quot;content__static___rRwvv utilities__overflowHidden___2947E&quot;]/div[1]/div[@class=&quot;paymentDetails__container___3r3rK&quot;]/div[@class=&quot;paymentDetails__addPaymentToggleContainerNarrow___1wROk paymentDetails__addPaymentToggleContainer___1LEIW&quot;]/div[1]/div[@class=&quot;content__static___rRwvv utilities__overflowHidden___2947E&quot;]/div[1]/div[@class=&quot;paymentDetails__addPaymentFormContainerNarrow___bBPVd layout__adaptiveGutterPaddingVertical___3o01V layout__adaptiveGutterPaddingTop___3ragO layout__adaptiveGutterPaddingBottom___2c1nd GutterDiv-uPqzs bOPyiR&quot;]/div[@class=&quot;form__container___31zeP utilities__relative___1GEg3&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;containers__formVerticalSpacingAdaptive___2TxXH&quot;]/div[@class=&quot;creditCardFields__thirds___3J0_p containers__containerBorderCollapse___1PVDW utilities__flexContainer___2sCJV&quot;]/div[3]/label[@class=&quot;textInput__container___1SC_K utilities__relative___1GEg3 utilities__block___2NUBz layout__heightControlAdaptive___3k245 utilities__fullWidth___3kUCi textInput__containerValid___3KDT5&quot;]/input[@class=&quot;textInput__input___cxJ09 utilities__resetBox___2gA-8 utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9 typography__inputCopy___dUIAv typography__copy14___3VCcc textInput__inputWithLabel___2uQ69&quot;]</value>
   </webElementProperties>
</WebElementEntity>
