<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rect_Save_for_future_use</name>
   <tag></tag>
   <elementGuidId>1421b9b4-0f70-456d-bb76-c8c647b4667a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@width = '43' and @height = '43']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>rect</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>43</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>43</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>#ffffff</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>#1f1f1f</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn&quot;]/ul[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/li[@class=&quot;modalStack__cover___3nTRc utilities__fixed___1nM3D utilities__cover___WKDvY utilities__listUnstyled___2AX2M&quot;]/div[@class=&quot;sheet__container___1Dstb utilities__fixed___1nM3D utilities__cover___WKDvY utilities__flexCenterBoth___bT52v utilities__flexContainer___2sCJV&quot;]/div[@class=&quot;sheet__main___1kYW3 utilities__fixed___1nM3D utilities__cover___WKDvY&quot;]/div[@class=&quot;sheet__content___2An5_ utilities__absolute___2Nj_S utilities__cover___WKDvY&quot;]/div[@class=&quot;layout__adaptiveGutterPaddingBottom___2c1nd GutterDiv-uPqzs bOPyiR&quot;]/div[@class=&quot;utilities__relative___1GEg3&quot;]/div[@class=&quot;form__container___31zeP utilities__relative___1GEg3&quot;]/div[1]/div[@class=&quot;addNewCreditCard__saveCheckbox___1uLZx typography__copy14___3VCcc&quot;]/div[@class=&quot;checkbox__container___1MJPx utilities__flexCenterVertical___2nEt- utilities__flexContainer___2sCJV utilities__fullWidth___3kUCi&quot;]/div[@class=&quot;checkbox__checkbox___2_B5M utilities__fullHeight___NZTu9 utilities__flexCenterVertical___2nEt- utilities__flexContainer___2sCJV utilities__pointer___1ctfY&quot;]/div[1]/svg[@class=&quot;icon__svg___cc1CR utilities__block___2NUBz utilities__fullWidth___3kUCi utilities__fullHeight___NZTu9&quot;]/rect[1]</value>
   </webElementProperties>
</WebElementEntity>
