<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Main</name>
   <tag></tag>
   <elementGuidId>a06ae01a-5f70-4219-90ad-898b9312ee03</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Main</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;app__container___1iszn undefined&quot;]/div[@class=&quot;Drawer__OuterDiv-fQULRK utilities__cover___WKDvY jxeJTN&quot;]/div[@class=&quot;Drawer__InnerDiv-QSCgb jfPdeQ&quot;]/div[@class=&quot;DrawerDiv-ihhGLG ZybrZ&quot;]/div[@class=&quot;TopBar__OuterDiv-eyXjzZ iGkRYN&quot;]/div[@class=&quot;JustifiedBar__OuterDiv-cTCyOC dKaHqT&quot;]/div[@class=&quot;JustifiedBar__LeftDiv-ebIrmq eNLYpj&quot;]/div[@class=&quot;TopBar__BackClickable-chiXyC typography__copy14___3VCcc typography__bold___1hpib utilities__bold___3ltf7 typography__uppercase___378Zu utilities__uppercase___3lD3P fDBbOR utilities__pointer___1ctfY&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
